import Image from "next/image";
import type { Metadata } from "next";

import styles from "./page.module.css";
import SiteSearch from "@/components/search";

export const metadata: Metadata = {
  title: "Guilherme's React 19, Next.js 15 skills",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <SiteSearch />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/samuraiguilherme"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/globe.svg"
            alt="Globe icon"
            width={16}
            height={16}
          />
          Go to my Github →
        </a>
      </footer>
    </div>
  );
}
